source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, '10.0'
target 'SwiftBluetoothKit' do
    use_frameworks!

    pod 'RxBluetoothKit'


    target 'SwiftBluetoothKitTests' do
        #Pods for Testing.
    end
end
