source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

platform :ios, '10.0'
target 'MockBluetoothKit' do
    use_frameworks!

    pod 'SwiftBluetoothKit', :path => '../..'

    target 'MockBluetoothKitTests' do
      #Add Pod dependency for Test Target
    end

end
